---
stages:
  - test

image: quay.io/ansible/molecule:2.20.1

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  ANSIBLE_FORCE_COLOR: "true"
  PY_COLORS: 1
  GIT_CLONE_PATH: $CI_BUILDS_DIR/apollo13.borgbackup
  GIT_DEPTH: 1

services:
  - docker:dind

molecule:
  stage: test
  script:
    - python -V
    - ansible --version
    - molecule --version
    - molecule test
