---
language: python
os: linux

services: docker

branches:
  only:
    - master

env:
  global:
    - ROLE_NAME: borgbackup
    - MOLECULE_DISTRO: centos:8

install:
  # Install test dependencies.
  - pip install molecule[ansible,docker,test,lint]

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME apollo13.$ROLE_NAME
  - cd apollo13.$ROLE_NAME

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
