---

- name: Download borgbackup
  get_url:
    url: https://github.com/borgbackup/borg/releases/download/{{ borgbackup_upstream_version }}/borg-linux64
    dest: /usr/local/bin/borg
    checksum: "{{ borgbackup_upstream_checksum }}"
    mode: 0755

- name: Remove system version
  package:
    name: "{{ borgbackup_system_package_name }}"
    state: absent
