---

- name: Install borgbackup via system package manager
  block:

    - name: Enable EPEL
      yum:
        name: epel-release
        state: present
      when: ansible_os_family == "RedHat" and borgbackup_install_method == 'system'

    - name: Install borgbackup
      package:
        name: "{{ borgbackup_system_package_name }}"
        state: present

    - name: Remove upstream version
      file:
        name: /usr/local/bin/borgbackup
        state: absent

  when: borgbackup_install_method == 'system'

- name: Install borgbackup from upstream sources
  block:

    - name: Download borgbackup
      get_url:
        url: https://github.com/borgbackup/borg/releases/download/{{ borgbackup_upstream_version }}/borg-linux64
        dest: /usr/local/bin/borgbackup
        checksum: "{{ borgbackup_upstream_checksum }}"
        mode: 0755

    - name: Remove system version
      package:
        name: "{{ borgbackup_system_package_name }}"
        state: absent

  when: borgbackup_install_method == 'upstream'
