---

- name: Enable EPEL
  yum:
    name: epel-release
    state: present
  when: ansible_os_family == "RedHat" and ansible_distribution != "Fedora"
  # Hack for https://github.com/ansible/ansible/issues/64963 to make action idempotent
  changed_when: False

- name: Install borgbackup
  package:
    name: "{{ borgbackup_system_package_name }}"
    state: present

- name: Remove upstream version
  file:
    name: /usr/local/bin/borg
    state: absent
