---

- name: Create borg repository root
  file:
    path: "{{ borgbackup_repository_storage }}"
    state: directory
    owner: "{{ borgbackup_user }}"
    group: "{{ borgbackup_user }}"
    mode: 0700
