---

- name: Create borg repository root
  file:
    path: "{{ borgbackup_repository_storage }}"
    state: directory
    owner: "{{ borgbackup_user }}"
    group: "{{ borgbackup_user }}"
    mode: "0700"

- name: Configure access to all repositories via management keys
  authorized_key:
    user: "{{ borgbackup_user }}"
    state: present
    key: "{{ item }}"
    key_options: >-
      command="
      cd {{ borgbackup_repository_storage }};
      {{ borgbackup_executable }} serve
      --restrict-to-path {{ borgbackup_repository_storage }}
      ",restrict'
  loop: "{{ borgbackup_management_keys }}"
  loop_control:
    label: "{{ item.split(' ', 2)[-1] }}"
  when: borgbackup_management_keys is defined

- name: Install borg compact service file
  template:
    src: "{{ item }}.j2"
    dest: /etc/systemd/system/{{ item }}
    mode: "0644"
  loop:
    - borgbackup-compact.service
    - borgbackup-compact.timer
  notify: Reload systemd

- name: Flush handlers to reload systemd
  meta: flush_handlers

- name: Enable systemd timer service
  systemd:
    name: borgbackup-compact.timer
    enabled: "{{ borgbackup_compact_timer_enabled }}"
    state: "{{ borgbackup_compact_timer_state }}"
