---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos_borgbackup_system
    image: centos:7
    groups:
      - system
  - name: centos_borgbackup_upstream
    image: centos:7
    groups:
      - upstream
  - name: ubuntu_borgbackup_system
    image: ubuntu:18.04
    groups:
      - system
  - name: ubuntu_borgbackup_upstream
    image: ubuntu:18.04
    groups:
      - upstream
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      upstream:
        borgbackup_install_method: upstream

verifier:
  name: testinfra
  lint:
    name: flake8
