---

_platform_defaults: &platform_defaults
  networks:
    - name: borgbackup_molecule
  privileged: True
  command: /sbin/init

dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: borg
    image: centos:7
    groups:
      - client
    <<: *platform_defaults
  - name: borg-centos-system
    image: centos:7
    groups:
      - client
    <<: *platform_defaults
  - name: borg-centos-upstream
    image: centos:7
    groups:
      - client
    <<: *platform_defaults
  - name: borg-ubuntu-system
    image: ubuntu:18.04
    groups:
      - client
    <<: *platform_defaults
  - name: borg-ubuntu-upstream
    image: ubuntu:18.04
    groups:
      - client
    <<: *platform_defaults
  - name: borg-srv-centos
    image: centos:7
    groups:
      - server
    <<: *platform_defaults
  - name: borg-srv-ubuntu
    image: ubuntu:18.04
    groups:
      - server
    <<: *platform_defaults
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      borg:
        borgbackup_calendar_spec: "*-*-* 8:00:00"
        borgbackup_passphrase: test
        borgbackup_known_hosts:
          - "dummy ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIElvcKplWycItag/MP7gYUCy95WIhMM1OFKbZ/j/ykFE"
        borgbackup_repository: ssh://borg@borg-srv-centos/./
        borgbackup_user: test

      borg-centos-system:
        borgbackup_passphrase: test
        borgbackup_repository_server: borg-srv-centos
        borgbackup_user: centos

      borg-centos-upstream:
        borgbackup_passphrase: test
        borgbackup_repository_server: borg-srv-centos
        borgbackup_install_method: upstream
        borgbackup_user: centos

      borg-ubuntu-system:
        borgbackup_passphrase: test
        borgbackup_repository_server: borg-srv-ubuntu

      borg-ubuntu-upstream:
        borgbackup_passphrase: test
        borgbackup_repository_server: borg-srv-ubuntu
        borgbackup_install_method: upstream

      borg-srv-centos:
        borgbackup_repository_storage: /var/borg
        borgbackup_management_keys:
          - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIElvcKplWycItag/MP7gYUCy95WIhMM1OFKbZ/j/ykFE adminuser"

      borg-srv-ubuntu:
        borgbackup_install_method: upstream
        borgbackup_user: test
        borgbackup_repository_storage: /var/borg
verifier:
  name: testinfra
  lint:
    name: flake8
