---

_platform_defaults: &platform_defaults
  networks:
    - name: borgbackup_molecule
  privileged: true
  command: /sbin/init
  volumes:
    - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  tmpfs:
    # disabled because it is mounted as noexec which breaks the borg upstream binary
    # - /tmp
    - /run
  tty: True
  environment:
    container: docker

dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: borg
    image: ${MOLECULE_DISTRO:-centos:8}
    groups:
      - client
    <<: *platform_defaults
  - name: borg-system
    image: ${MOLECULE_DISTRO:-centos:8}
    groups:
      - client
    <<: *platform_defaults
  - name: borg-upstream
    image: ${MOLECULE_DISTRO:-centos:8}
    groups:
      - client
    <<: *platform_defaults
  - name: borg-srv
    image: ${MOLECULE_DISTRO:-centos:8}
    groups:
      - server
    <<: *platform_defaults
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      borg:
        borgbackup_calendar_spec: "*-*-* 8:00:00"
        borgbackup_passphrase: test
        borgbackup_known_hosts:
          - "dummy ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIElvcKplWycItag/MP7gYUCy95WIhMM1OFKbZ/j/ykFE"
        borgbackup_repository: ssh://borg@borg-srv/./
        borgbackup_user: test

      borg-system:
        borgbackup_passphrase: test
        borgbackup_repository_server: borg-srv
        borgbackup_user: test

      borg-upstream:
        borgbackup_passphrase: test
        borgbackup_repository_server: borg-srv
        borgbackup_install_method: upstream
        borgbackup_user: test

      borg-srv:
        borgbackup_repository_storage: /var/borg
        borgbackup_management_keys:
          - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIElvcKplWycItag/MP7gYUCy95WIhMM1OFKbZ/j/ykFE adminuser"

verifier:
  name: testinfra
  lint:
    name: flake8
