---

_platform_defaults: &platform_defaults
  networks:
    - name: borgbackup_molecule
  privileged: True

dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos-borgbackup-system
    image: centos:7
    command: /sbin/init
    groups:
      - client
    <<: *platform_defaults
  - name: centos-borgbackup-upstream
    image: centos:7
    command: /sbin/init
    groups:
      - upstream
      - client
    <<: *platform_defaults
  - name: ubuntu-borgbackup-system
    image: ubuntu:18.04
    command: /sbin/init
    groups:
      - client
    <<: *platform_defaults
  - name: ubuntu-borgbackup-upstream
    image: ubuntu:18.04
    command: /sbin/init
    groups:
      - upstream
      - client
    <<: *platform_defaults
  - name: centos-server
    image: centos:7
    command: /sbin/init
    groups:
      - server
    <<: *platform_defaults
  - name: ubuntu-server
    image: ubuntu:18.04
    command: /sbin/init
    groups:
      - server
    <<: *platform_defaults
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      upstream:
        borgbackup_install_method: upstream
      client:
        borgbackup_config:
          calendar_spec: "*-*-* 2:00:00"
          repository: file:///home/backup/test_repo
          passphrase: test
          known_hosts:
            - "dummy ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIElvcKplWycItag/MP7gYUCy95WIhMM1OFKbZ/j/ykFE"
          repository_server: centos-server
      server:
        borgbackup_repository_storage: /var/borg

verifier:
  name: goss
  lint:
    name: yamllint
