---

_platform_defaults: &platform_defaults
  networks:
    - name: borgbackup_molecule
  privileged: True

dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: borg
    image: centos:7
    command: /sbin/init
    groups:
      - client
    <<: *platform_defaults
  - name: borg-centos-system
    image: centos:7
    command: /sbin/init
    groups:
      - client
    <<: *platform_defaults
  - name: borg-centos-upstream
    image: centos:7
    command: /sbin/init
    groups:
      - client
    <<: *platform_defaults
  - name: borg-ubuntu-system
    image: ubuntu:18.04
    command: /sbin/init
    groups:
      - client
    <<: *platform_defaults
  - name: borg-ubuntu-upstream
    image: ubuntu:18.04
    command: /sbin/init
    groups:
      - client
    <<: *platform_defaults
  - name: borg-srv-centos
    image: centos:7
    command: /sbin/init
    groups:
      - server
    <<: *platform_defaults
  - name: borg-srv-ubuntu
    image: ubuntu:18.04
    command: /sbin/init
    groups:
      - server
    <<: *platform_defaults
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      borg:
        borgbackup_config:
          calendar_spec: "*-*-* 8:00:00"
          repository: ssh://backup@borg-srv-centos/./
          passphrase: test
          known_hosts:
            - "dummy ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIElvcKplWycItag/MP7gYUCy95WIhMM1OFKbZ/j/ykFE"
          autoinit: no
        borgbackup_user: test

      borg-centos-system:
        borgbackup_config:
          repository: ssh://backup@borg-srv-centos/./
          passphrase: test
          repository_server: borg-srv-centos
        borgbackup_user: centos

      borg-centos-upstream:
        borgbackup_config:
          repository: ssh://backup@borg-srv-centos/./
          passphrase: test
          repository_server: borg-srv-centos
        borgbackup_install_method: upstream
        borgbackup_user: centos

      borg-ubuntu-system:
        borgbackup_config:
          repository: ssh://test@borg-srv-ubuntu/./
          passphrase: test
          repository_server: borg-srv-ubuntu

      borg-ubuntu-upstream:
        borgbackup_config:
          repository: ssh://test@borg-srv-ubuntu/./
          passphrase: test
          repository_server: borg-srv-ubuntu
        borgbackup_install_method: upstream

      borg-srv-centos:
        borgbackup_repository_storage: /var/borg

      borg-srv-ubuntu:
        borgbackup_install_method: upstream
        borgbackup_user: test
        borgbackup_repository_storage: /var/borg
verifier:
  name: testinfra
  lint:
    name: flake8
