---

- name: Install borgbackup
  hosts: all

  roles:
    - borgbackup

- name: Configure clients
  hosts: client

  tasks:

    - name: Configure working backup
      include_role:
        name: borgbackup
        tasks_from: configure.yml
      vars:
        service: test_working
        backup_user: root
        backup_command: /bin/true
        paths:
          - /etc
      when: '"centos" in inventory_hostname'

    - name: Configure failing backup
      include_role:
        name: borgbackup
        tasks_from: configure.yml
      vars:
        service: test_failing
        backup_user: root
        backup_command: /bin/false
        paths:
          - /home
      when: '"ubuntu" in inventory_hostname'
