---

- name: Install & configure Borg
  hosts: all

  roles:
    - borgbackup

- name: Configure clients
  hosts: client

  tasks:

    - name: Configure working backup
      include_role:
        name: borgbackup
        tasks_from: configure.yml
      vars:
        service: test_working
        backup_user: root
        backup_command: /bin/sh -c "/bin/sleep 5 && /bin/true"
        paths:
          - /etc

    - name: Configure failing backup
      include_role:
        name: borgbackup
        tasks_from: configure.yml
      vars:
        service: test_failing
        backup_user: root
        backup_command: /bin/sh -c "/bin/sleep 2 && /bin/false"
        paths:
          - /home
