---

- name: Converge
  hosts: all

  tasks:
    - import_role:
        name: borgbackup

    - name: Configure working backup
      include_role:
        name: borgbackup
        tasks_from: configure.yml
      vars:
        service: test_working
        backup_user: root
        backup_command: /bin/true
        paths:
          - /etc
