---

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ROLE_NAME: apollo13.borgbackup

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        molecule-distro:
          - "centos:7"
          - "rockylinux:9"
          - "ubuntu:18.04"
          - "ubuntu:22.04"
          - "debian:bookworm"
          - "fedora:38"

    env:
      MOLECULE_DISTRO: ${{ matrix.molecule-distro }}

    steps:
      - name: Configure variables
        run: echo "::set-output name=checkout_path::$ROLE_NAME"
        id: config

      - uses: actions/checkout@v2
        with:
          path: ${{ steps.config.outputs.checkout_path }}

      - uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install wheel
          python -m pip install ansible molecule[testinfra] molecule-plugins[docker] yamllint ansible-lint flake8

      - name: Molecule test
        run: |
          cd $ROLE_NAME
          molecule test
